name: Node.js CI

on:
  push:
    branches: [ Develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.10.0'
    - name: Install dependencies
      run: npm install

